import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const requests = [
  {
    id: "seed_rearrange_dashboard_widgets",
    title: "Rearrange dashboard widgets",
    description:
      "Operations managers scan the dashboard several times a day, but their most important KPIs sit below less relevant panels. Let each user drag, resize, and reorder widgets, then preserve that layout for their next visit.",
    supportCount: 29,
    createdAt: new Date("2026-09-04T14:30:00.000Z"),
  },
  {
    id: "seed_granular_permission_controls",
    title: "Add granular permission controls",
    description:
      "Workspace owners need to control project access without giving every collaborator the same capabilities. Provide separate permissions for viewing, commenting, editing, and exporting sensitive project information.",
    supportCount: 35,
    createdAt: new Date("2026-09-01T16:15:00.000Z"),
  },
  {
    id: "seed_download_analytics_csv",
    title: "Download analytics data in CSV format",
    description:
      "Data analysts want to inspect the raw records behind dashboard charts in their own spreadsheet models. Add a CSV download that includes the active dashboard date range and filters without requiring manual copy and paste.",
    supportCount: 18,
    createdAt: new Date("2026-08-29T13:00:00.000Z"),
  },
  {
    id: "seed_notification_preferences",
    title: "Manage notification preferences",
    description:
      "Individual contributors receive product emails that are not equally relevant to their work. Give each person a preferences page where they can mute noisy categories while retaining updates for mentions and requests assigned to them.",
    supportCount: 14,
    createdAt: new Date("2026-08-27T17:45:00.000Z"),
  },
  {
    id: "seed_customizable_dashboards",
    title: "Build customizable dashboards",
    description:
      "Product leaders track different outcomes depending on their portfolio and reporting cycle. Allow them to choose the metrics and report sections shown on the overview dashboard and save the result as their default view.",
    supportCount: 11,
    createdAt: new Date("2026-08-24T15:20:00.000Z"),
  },
  {
    id: "seed_custom_user_roles",
    title: "Create custom user roles",
    description:
      "Enterprise administrators need access profiles that match teams such as finance, support, and regional operations. Let admins define named roles with a reusable set of capabilities instead of relying only on the standard admin and member roles.",
    supportCount: 22,
    createdAt: new Date("2026-08-22T12:10:00.000Z"),
  },
  {
    id: "seed_configurable_email_notifications",
    title: "Configurable email notifications",
    description:
      "Team leads want more control over the email generated by activity in their workspaces. Allow them to select which events trigger a message and whether updates arrive immediately or in a daily digest.",
    supportCount: 27,
    createdAt: new Date("2026-08-19T18:05:00.000Z"),
  },
  {
    id: "seed_export_reports_csv",
    title: "Export reports as CSV",
    description:
      "Customer success managers share monthly account-health reports with leadership and need to continue working with the results offline. Add a CSV export for the full report table that preserves the selected filters and reporting period.",
    supportCount: 32,
    createdAt: new Date("2026-08-16T14:40:00.000Z"),
  },
];

async function main() {
  const result = await prisma.featureRequest.createMany({
    data: requests,
    skipDuplicates: true,
  });

  console.log(`Seeded ${result.count} feature request(s).`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
